### ISSUE TITLE
백준 2261 문제 

### ISSUE THREAD

**Issue by sjang42** [algorithm-011/problem-solving#4]
광희님이 설명해주셨던건데 잘 안풀려서 [풀이](https://m.blog.naver.com/PostView.nhn?blogId=jung2381187&logNo=220867501554&proxyReferer=https%3A%2F%2Fwww.google.co.kr%2F)보면서 이해하고 있습니다.
링크에 나오는 풀이가 다른 건 이해가 가는데 [이 그림](http://m.photoviewer.naver.com/blog?listUrl=https%3A%2F%2Fm.blog.naver.com%2FPostView.nhn%3FblogId%3Djung2381187%26logNo%3D220867501554&imgId=3&host=https%3A%2F%2Fm.blog.naver.com%2Fphotoviewer&historyBack=true&blogId=jung2381187&logNo=220867501554#main/3)에서 왜 직사각형 안에 항상 **6개** 이하의 점만이 존재할 수 있는건지 궁금합니다..

**Comment by juice500ml** [comment]
![image](https://user-images.githubusercontent.com/7028312/38159728-70b62eca-34e9-11e8-9f25-8a95d129b43f.png)
d*2d 직사각형에서 d 이하 거리를 갖는 점의 갯수는 최대 6개입니다.

**Comment by juice500ml** [comment]
참고) d-dimensional http://www.cs.ucsb.edu/~suri/cs235/ClosestPair.pdf

**Comment by sjang42** [comment]
기준 선의 각각 양쪽에서 두 점의 거리가 최소 d가 되야하니 위 그림이 최고 많이 들어가는 경우군요 ㅋㅋ 감사합니다 이해했어요
